name: Jenkins Pipeline (Self-Hosted Simulation)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jenkins-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend1/package-lock.json
      - name: Stage 1: Checkout (Jenkins Simulation)
        run: |
          echo "=== Jenkins Pipeline Stage: Checkout ==="
          echo "Building commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Workspace: $(pwd)"
          
      - name: Stage 2: Backend Build & Test (Jenkins Simulation)
        run: |
          echo "=== Jenkins Pipeline Stage: Backend Build & Test ==="
          cd backend
          
          # Clean and install dependencies
          echo "Running: ./mvnw clean install -DskipTests"
          ./mvnw clean install -DskipTests
          
          # Run unit tests
          echo "Running: ./mvnw test"
          ./mvnw test
          
          # Run integration tests
          echo "Running: ./mvnw verify -Dspring.profiles.active=test"
          ./mvnw verify -Dspring.profiles.active=test
          
          # Archive test results (Jenkins simulation)
          echo "Archiving test results..."
          mkdir -p ../jenkins-artifacts/backend
          cp -r target/surefire-reports ../jenkins-artifacts/backend/ || echo "No test reports found"
          
      - name: Stage 3: Frontend Build & Test (Jenkins Simulation)
        run: |
          echo "=== Jenkins Pipeline Stage: Frontend Build & Test ==="
          cd frontend1
          
          # Install dependencies
          echo "Running: npm ci --cache ~/.npm --prefer-offline"
          npm ci --cache ~/.npm --prefer-offline
          
          # Run unit tests
          echo "Running: npm test -- --watch=false --browsers=ChromeHeadless"
          npm test -- --watch=false --browsers=ChromeHeadless
          
          # Build production bundle
          echo "Running: npm run build"
          npm run build
          
          # Archive build artifacts (Jenkins simulation)
          echo "Archiving build artifacts..."
          mkdir -p ../jenkins-artifacts/frontend
          cp -r dist ../jenkins-artifacts/frontend/ || echo "No dist folder found"
          
      - name: Stage 4: E2E Smoke Tests (Jenkins Simulation)
        run: |
          echo "=== Jenkins Pipeline Stage: E2E Smoke Tests ==="
          cd frontend1
          
          # Install Playwright browsers
          echo "Installing Playwright browsers..."
          npx playwright install --with-deps
          
          # Build frontend for testing
          echo "Building frontend for testing..."
          npm run build
          
          # Start frontend server
          echo "Starting frontend server..."
          npx serve -l 4200 dist/frontend1/browser &
          sleep 15
          
          # Wait for server to be ready with multiple attempts
          echo "Waiting for server to be ready..."
          for i in {1..5}; do
            if curl -f http://localhost:4200 > /dev/null 2>&1; then
              echo "Server is ready!"
              break
            else
              echo "Attempt $i: Server not ready, waiting..."
              sleep 5
            fi
          done
          
          # Final check
          curl -f http://localhost:4200 || echo "Server still not ready, but continuing..."
          
          # Run only smoke tests (critical path)
          echo "Running smoke tests..."
          npx playwright test e2e/tests/smoke.spec.ts --reporter=list --timeout=60000 --workers=4
          
          # Archive E2E test results (Jenkins simulation)
          echo "Archiving E2E test results..."
          mkdir -p ../jenkins-artifacts/e2e
          cp -r playwright-report ../jenkins-artifacts/e2e/ || echo "No playwright report found"
          cp -r test-results ../jenkins-artifacts/e2e/ || echo "No test results found"
          
      - name: Stage 5: Deploy Backend (Railway) - Skipped
        run: |
          echo "=== Jenkins Pipeline Stage: Deploy Backend (Railway) ==="
          echo "Railway deployment skipped - token not configured"
          echo "When Railway token is available, uncomment deployment code in Jenkinsfile"
          
      - name: Stage 6: Deploy Frontend (Railway) - Skipped
        run: |
          echo "=== Jenkins Pipeline Stage: Deploy Frontend (Railway) ==="
          echo "Railway deployment skipped - token not configured"
          echo "When Railway token is available, uncomment deployment code in Jenkinsfile"
          
      - name: Upload Jenkins Pipeline Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jenkins-pipeline-artifacts
          path: |
            jenkins-artifacts/
          retention-days: 30
          
      - name: Pipeline Success Notification
        if: success()
        run: |
          echo "=== Jenkins Pipeline Completed Successfully! 🎉 ==="
          echo "All stages passed:"
          echo "✅ Checkout"
          echo "✅ Backend Build & Test"
          echo "✅ Frontend Build & Test"
          echo "✅ E2E Smoke Tests"
          echo "⏭️  Deploy Backend (Skipped - no Railway token)"
          echo "⏭️  Deploy Frontend (Skipped - no Railway token)"
          
      - name: Pipeline Failure Notification
        if: failure()
        run: |
          echo "=== Jenkins Pipeline Failed! ❌ ==="
          echo "Check the logs above for details on which stage failed."
